# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.parallel=true
kotlin.daemon.jvm.options=-Xmx2G

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_kotlin_version=1.13.13+kotlin.2.4.10

# Mod Properties
version=0.8.12+v21.0.3.0
group=com.vulkairis

# Dependencies
fabric_api_version=0.116.17+1.21.1
iris=1.8.14-beta.1+mc1.21.1
vulkanmod=0.6.7+1.21.1
